language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- npm install
- make build
deploy:
  skip_cleanup: true
  provider: s3
  local_dir: dist
  bucket: listenpte.com
  region: ap-southeast-2
env:
  global:
  - secure: nDVcFdzRnWYY9jI0Znn8XEvLLVlC2VbQvjf43OuGMtJywvnypZVdbYRWMzUxQ2do8DfBky+4Vz3ZFHCLlopzOV9YRlaWQLeFYIgBLUC4A8aT8L3ocWH0z91J3cJ0ALMSwzPLAHYObYMm+7K28lNqzL6YK8WTK4TljBE03vb0t502K7H2gq+9bNorGBM3Fg6F9YeMGEmL44X8TM9TgomdMvPV31TWNHinAbOENgCH+tX2Z3uV3HKFmKm0DiDX+5ufJQV2+tgsm3clIkvwqEHwMZ9WpKiMHtRjZNq3D3WRf2IH8x4slU9so7P4oz0F7zYQwlB6/8d0kgRIS1ZcQPwHzJby5uG3bFoUIMV8Ee7Egrjq1k6uHNzJxJB+sNAkHZkw9xJpTUvkBSFrvF9C08wSCLIwydDgV+02N0FbiPZwRir0Whh9Rna8v+MZi1XegSGcFOWfTqvScdac1+tsNTmKogxVF47zSy+H8MKJfgghpU4uczHBziE/QfXfvv7nZqNOwiyPX+nVwlMRND7pz1dB8qS3r29iWF2DMtDFUKrbOicTkak/WW2TcvoyShsdtEB6OIwZwzLjGWds1/MUxcDO6LNTMmAPxw7Y0aMMfXkcaOuKj/EqCoYuSiOREUWuvNZssZzWHOaydNdmDjhfz8WZquNLMvqjQ07I3tL0vn5z0x8=
  - secure: prkvXN6H3vwEOr/Uq7+ynW15yYyEZ+m9NphzxWj4w9L80rmgGhyxldGcsqGfo6O4SJOVDO+Vli9zLf8KWeve6cx7tGf7EcuvRyhMC95SrWj2H5r03Kkm8Uu5XqBUNOa29C4NcQUn3Rmu99+EvyCEttISa/k+4v0JVtm7Y4UxiWlBmnjOH68o+qYTjKGfa1+jh/M20RtX/fpqm9gr3Mnuh+XVaJns1sKgnqI62LKhiaHc1P7qkRFHnahOGniJv+l5Ai2BU70D6Ca/0pWhtcFwYVurWdA8zIAPKCBTWb1rWre/JSQUDl5893RVn0g/F9cXtteV1+SfY+eXRnK2l85z1qhVVjEIEzAF4MQBULENdsGWA2z6QrxRe8RdxSHIgIT3v3tMNsnHoRw2C+ANsKh0K9OWFpRZQY7aHntqISnVBNc8912zfDyjKZ6N3LjOWq/LIv1ByXj22yJ0IHNIUBTfXLoPau0teFMr5HNAS14R8uyTsdv0+fWMM1t6yoaemm2I/uZxiIpaRurE3/3XAnum7YLw7umPWQT/aIPzvUHxVQ6NLMWC+2bVIlv2CDbUic/bFqbbeIOyGQT7eMNzaQ1gQaIoYwrnMgUiV0eGWRuxXDiXneOs9MZI0i5Ith9MSNiApuP8hVXJF8icFzWX83QBYfaeGh1+xF/cHgkNNjS4Fr4=
