language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- npm install
- make build
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: mQ60fAyJ81C378ZD8VTceDwa6txRGqtDoOyamVVdoLYtvNQ/r854m7pAfcqrHr6wl4W0CaR2+ccGolXoRcrIAfPF58AhC9jVZ4nti62XvhGmYlCjo4/1fh/AXxuGJZFKTsx/rbpQ2m/5lG0xoYGHGLIux4UyKZ1cFvYVocepyHbNoGevcZSmuF1WWOuBYp/pYplq/WhkrXOya2AgTwvOLxZYWJg3S426brwGn3oqiQjBypyPiPvJNx2flAUE6BVYhKJToatj66zoUPRlgPq7KDbzIv77ZAqfmshkpB6keGq3oGogn6hkNYXtkMZOuuG8x7+5zE1IToN+vma8cBzDIpTRF6TCP67Y9k3+AJpr60u7JRMYLKC9s9bDV758ZfrSUHQRY7G8IAwr11xikFOn306QN9cebJ/aOrqDI2730h31B329ELPwDS/9gVxw+jOzdJcULMGkbUC0E4GRjfRm/UvdibVo8UtB1Wu+CqmoeuXLxkkVk3rR5L4wXbP92Mc08/8plEHddw7VC1r5oj/GTe/89QCNiaX+4wNt7xLodZnLfAkzj+FQ+ZURIOPVdwrZhze3kS2/8FSTu9W7S+sIsYAZEM8ZDrQK6zY3I/r74m7PbbWeRY9DTiWWu/+TjvMrvDnpBYG5OW/4rpEPdDnOtEL7GsRDlDeC088b4zmY0Zg=
  - secure: auK4hBd2JBoxUkx7SLurJGfDjbBAg91nSDVrw/oeB2gR4RFBq5LNetdJ3CbptMpxUnzbrJXg8Q/7SIhSi4WTp15hbZOdE2SUdb+Vm7ri8qwc/nLO7Psud2wLL+9RFmnSErWwBJp8kRRwLEEHPSQVBi3evn1ndRuWDFdykOHsJSNvPkG9RVRcPgImbXhTk8T79j5l5UA+jE64VhHuLSWkMLgZCKZ1ASy0RosIesnc+d7N+DAmK7tRKagNTkVrD9ml1+Vqr++OtVVehQq57+e3yv6yAZJlvYP3sSZVCzxugbSBfmGM5DWBP3KukYHjfFAgOKkvYaS/j9CS9pDjT7h5Bs7KA+2zAq/45oH25fj2627oGOaAZwjh7Dh+xYqk/GuPM0MZBh+qMP3BCWEJoKQjWLDUtpheAT1A/R8XD0CpOFSWC4jitA3qlTfJxMEO2xtYnYyRL9ZfXOU5DeVPoa39rg8d7ap52pDGS1EJrFsHNzuewH4Rd6O85UOyivQU8ZwtE5y6Z7AvWVJLR18iYzfWY+DECxadwCWJ1P1EOPNY147H53a/ZerluEW9ReKIuHR4guZoP1muP9CMu4potUFkfdBY7LXKIzSTzU0yiRC9tg6gGUqAd2LqEcmKM6jBP3bVb7K8IMb7m5fm8T+DYT8bMG5aDgzfHDr+dOdnEAo6Z3I=
  - secure: ZaVmCa+H//a3jbYZI/kMXp3+oc8m8YzTWEPpUP1zFvZwYZ1mk71C1nREGpIjKaTFcODiU/6WkQI4+1MLz2aEZU4jxx48xP9wxutAxn6+4+ZYrlfusbKNFlGj4aGrXGdwt11FPDEJKMMhlOj2xdh8pHQWFILBqhkYEkcWRBqGt6DOa9UHfk9a29g7uF9cqYzH0sdqAnaCThWigPagGgZRsiMO3nMOB7PlqhkYOPgHpYqn3igLSI9GpUd/8JPj1C+1uJEE1iX4vx0XhM6dFqb05p8tYv7TKJStyVgbJjdfKX3JtFqNOfOLOrr8F1uFtrEHx++Rr/ucz2KsxSt+hi9Ba6G997Y5KvkzNFrAxLWpfCqPa0vCIfdNMsvx5q9Lh8xRqPhis8lrSq2XelIwi1OUE6L2avt5dpl4a4ZGtA8v+vRpTLP9Gd05xEEbWawE6vVMDzvVgzrqyyMJwuWyAaz9ufVNTOOUXhDfOF0CWQG6yPiyQMFUkFiCmhiVmLhE3yEGELXrl3nEQqyAjLLDz3qNnKuXJp7eWOClAZybbFmI2ch9jFm7i+KY+34/MXavLjoNi8bdCxB3qQk32bZ50iWSakICTG2ZHBbUeFI5eLbfL22m+ao5t2Xmd2jpyZjGzaQQnnK5WWoabM+qLKaHkGC6YDrkQEu0wbWOrV7zOZla0PE=
