language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- npm install
- make build
deploy:
  provider: s3
  access_key_id: AKIAIQE4AOX2KLSELCKA
  secret_access_key:
    secure: 4/ylP/YW72hoDEKVDvvcYJJ/6WTayGAwBh8h23ZAMKu7DfXOIuhzXartHcS02/q46n5z4a4pjz51RXhiBI6K1mUayhYgEPjJ8RvzK9ZBMH1rM/grJAFlxFxUdB6/T5CXTJKEwNMUkA34mMrvBrbMN/1q0Vq6hfHLbYYSHfHxYGkmCK0cm9m24tAjxGhZIJ9BikLhuYuteViTFqwYnq4K+L3S90VwKU+/reDXlvK209PlpXV/Xlah8kRv8QLTAyPJXBxnAOv6SfRbf5ZKM2X/qQDCHrkjLB++kWjWD31Xh0yRG87hFxz46LM0i9r3Eksebs9leQh7SBU7Uwy3cNixaOURrduKFKKTkk2s7NPBpFmIuFHmnpaeklzf45FhYNPcE+YlWP/VCXlWhU40WroCWCl06B1XVJsqxdioZlQP9+DpneDj19Ti21YEa5zyZC22PiJXTfV4c0vlfdX9mURXyQXWknuykQiz6uiTHy8JBAIb+8yoVjUxkN35cyQD70DWuQ6sfHrQGICuIpzcsG2S2Czm2B1PcqeT6SsaHqVo9uJU5iiCqFAl+RoGpNllmFPVBaIeEKfDefJ5ZEtw2Ak1YP/JSLem49QVZAIHnRbCJgcCgEjOFn/Tj7kHZQk0IMU6Fkd7BL+zyjIdyWADKqgVZmVaYWnp97JuqP1AmVYbtAU=
  bucket: listenpte.com
  local-dir: dist
  acl: public_read
  on:
    repo: neekey/www.listenpte.com
