language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- npm install
- make build
deploy:
  skip_cleanup: true
  provider: s3
  local_dir: dist
  bucket: listenpte.com
  region: ap-southeast-2
  access_key_id:
    secure: "ELiIBgLnnaWqVier+eJ2opnoC0rrGE2eJJ4YutkbCXUV6UJ6dAQhYtmumbAqezWhyfn1+6AMIGdfaV5ErJzqAzt75N6PMSeZRZqMp37mZtFQFXHcKDHPESDfCO2uB1XEa52HcM1Gg9Q9Sld3fPL58LIaPSD6zpB75Wc/EXxo4tOahFEL0W87NVw9yy917RjseVQG5nRTxoap2u80QS84xEWvPnk8FgbVpikC+IRokiEVn2eadqeUGpbSlSMk/xZTPudEMvj0jUuEdldWdKeAdDbNkc3CdJNEkbZfawlnGKnZwYLJmpF4RKgoP1ODO9t+eyR3E4bWx92ZDSfSeb6DDOi4CovfyG9lQ+xU8c5RizaUY7XBrEz3K8d8qf8kFEJDvzd4QjL+ochHmW1jYbiss9NVbutdnCTB10ZwFgp3Z57d0ACyZYssHMag5xgMRzbt20+xnaukDTjMG0OkpnPwRauLxKD003DxSZScbTafwmbypTplW1R9M1qXmU77oJYpUNIPLUCCEGF0QPjjhuDFUj0outQm3iEUl/+je8RmTR3RSkmNyYH1so+GYopKJdXWfEojCH2ruHIC7u1mB+GrX0iNQgcgWaYizokygX25gzOZZUHdlPJyOCgxH2uOh/qV9HOBO76YepcVannfayFQvUh5jXVdx43LpJCa08ylitQ="
  secret_access_key:
    secure: "ZCHJXwUpV8qhQ5CBygFQx2PJ7clF/gcv8o7g5p/AqRqluwOos/NIxPBHw2aby1/oWI2q899qDvSNxFs5aknKTo1Xy5oKEEDyXMXl7JeFu/diG9jXuYcE2kKc/VOzPaBc9EXKfXOA71qoUELnI2tJ+e3pgM7nPu1UaeR/Yca2qHwTYbwEbZqxkJHi33VtieP3Ttfpp18YgwwEnJftI1x9fdFpK4x6sGNJNsO3ZPlFevzbTsAILEMtBItU/CEmWOdA3m7oF8FXRWkHDtOJoxJBUOzX2mhxVIvWi9MSW4VP6L1CqKuWZTO7oQ96+cXZwoRQ/uP1ndmmANPUeOUFmh3HFRbbl4v96xC1Fi5wY6vUFIaHlgAHCFgWQd9SEVPFOjWoKBOvkW6ub2k6xqdeF5QquLboJBLfMS9tRMpPHB9auILqQo+Dk6E3L2+ER9VKbTJTdDVsLLDjKg4yWdXsKI0R7KEHG8xZgakvRuFQtjJcpDe3Xb0aF5763BEPo+NK7vg/bIvr+u+GytHea5SZmZnHDkaAum4tGJD+pjs+1AqTl96MVS/asJD6WQ1u2SmHD9hDZhkMrCONaRCOOHSuiCb13CuVZXSSWOmmC74NWlSaUhEEEuk3OdLgQdLRmHdGn+fLvDwO+68Zl6d1SSgKbF8095vDs1WonoV5t8nGuE6zc+s="
